ScreenManager:
    id: screen_manager
    firstpage:

<firstpage>:
    name: "First!"
    BoxLayout:
        canvas.before:
            Color: 
                rgba: (235/255, 235/255, 211/255, 1)
        orientation: "vertical"
        Button:
            text: "Sign In"
            background_color: 181/255, 214/255, 178/255, 1
        Button:
            text: "Look around as guest"
            background_color: 181/255, 214/255, 178/255, 1
